name: Doing it for DZ DevOps
on: [push]
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: pip install -r .github/workflows/requirements.txt
      - name: Run build
        run: docker build -t python-app .
      - name: Test
        run: .github/workflows/test.py
      - name: Ending
        run: echo "It’s my workflow"
